name: PR Verfification
on:
  pull_request:
    types: [opened, edited, ready_for_review, reopened, synchronize]

jobs:
  Verification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Branch
        run: |
          echo "$(git branch)"
          echo "$(git log -2 --oneline)"
      - name: Verify
        uses: tomasz-czyzak/demo-javascript-action/verify@develop
        with:
          who-to-greet: 'John Doe 11 Verify'
