name: PR Validation
on:
  pull_request:
    types: [opened, edited, ready_for_review, reopened]

jobs:
  pr_validation_job:
    runs-on: ubuntu-latest
    name: PR Validation Job
    steps:
      - name: Hello world action step
        id: hello
        uses: tomasz-czyzak/demo-javascript-action@develop
        with:
          who-to-greet: 'John Doe 11'
