name: PR Verfification
on:
  pull_request:
    types: [opened, edited, ready_for_review, reopened, synchronize]

jobs:
  changed_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

  verifyPR:
    runs-on: ubuntu-latest
    steps:
    - uses: tomasz-czyzak/demo-javascript-action/verify@develop
      with:
        who-to-greet: 'John Doe 11 Verify'
