name: PR Verfification
on:
  pull_request:
    types: [opened, edited, ready_for_review, reopened, synchronize]

jobs:
  verify_pr:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.changes.outputs.all }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: echo git
        id: echo
        run: echo "$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"

      - name: Get changed files
        id: changes
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
      - uses: tomasz-czyzak/demo-javascript-action/verify@develop
        with:
          who-to-greet: 'John Doe 11 Verify'
