name: PR Validation
on:
  pull_request:
    types: [opened, edited, ready_for_review, reopened]

jobs:
  pr_validation_job:
    runs-on: ubuntu-latest
    name: PR Validation Job
    steps:
      - name: Hello world action step
        id: hello
        uses: tomasz-czyzak/demo-javascript-action@v1.0.1
        with:
          who-to-greet: 'John Doe'
      # Use the output from the `hello` step
      - name: Completed
        run: echo "Completed:${{ steps.hello.outputs.time }}"
