name: PR Verfification
on:
  pull_request:
    types: [opened, edited, ready_for_review, reopened, synchronize]

jobs:
  changedFiles:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.changes.outputs.all}}
    - name: Changed files
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Branch
        run: |
          echo "$(git branch)"
          echo "$(git log -2 --oneline)"
      - name: Get changed file
        id: changes
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
          
   verifyPR:
      runs-on: ubuntu-latest
      needs: changedFiles
      steps:
      - name: echo changed files
        run: echo ${{needs.changedFiles.outputs.all }}
      - name: Verify
        uses: tomasz-czyzak/demo-javascript-action/verify@develop
        with:
          who-to-greet: 'John Doe 11 Verify'
