name: PR Validation
on:
  pull_request:
    types: [opened, edited, ready_for_review, reopened]

jobs:
  pr_validation_job:
    runs-on: ubuntu-latest
    name: PR Validation
    steps:
      - name: pr_validation_step
        uses: tomasz-czyzak/demo-javascript-action/verify@develop
        with:
          who-to-greet: 'John Doe 11 Verify'
