name: PR Verfification
on:
  pull_request:
    types: [opened, edited, ready_for_review, reopened, synchronize]

jobs:
  verify_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Get changed files
        id: changes
        run: |
          echo "::set-output name=modified_files::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
          
      - uses: tomasz-czyzak/demo-javascript-action/verify@develop
        with:
          modifed_files: ${{ steps.changes.outputs.modified_files }}"
